'use strict';module.exports=function(D,E){function F(v){function y(a){var f;a:{try{f=m.statSync(a);break a}catch(c){}f=!1}return f&&!f.isDirectory()?m.realpathSync(a,p._realpathCache):!1}function w(a,f){for(var c=0,l=f.length;c<l;c++){var h=y(a+f[c]);if(h)return h}return!1}function z(a){65279===a.charCodeAt(0)&&(a=a.slice(1));return a}var m=require("fs"),p=require("module"),s=require("path"),a={};p._realpathCache={};p._findPath=function(A,f){var c=Object.keys(p._extensions);"/"===A.charAt(0)&&(f=
[""]);var l="/"===A.slice(-1),h=JSON.stringify({request:A,paths:f});if(p._pathCache[h])return p._pathCache[h];f.push(v);for(var t=0,z=f.length;t<z;t++){var q=s.resolve(f[t],A),k;l||(k=y(q))||l||(k=w(q,c));if(!k){var n=q;k=c;var d;b:if(d=n,Object.prototype.hasOwnProperty.call(a,d))d=a[d];else{try{var x=s.resolve(d,"package.json"),r=m.readFileSync(x,"utf8")}catch(b){d=!1;break b}try{var u=a[d]=JSON.parse(r).main}catch(e){throw e.path=x,e.message="Error parsing "+x+": "+e.message,e;}d=u}d?(n=s.resolve(n,
d),k=y(n)||w(n,k)||w(s.resolve(n,"index"),k)):k=!1}k||(k=w(s.resolve(q,"index"),c));if(k)return p._pathCache[h]=k}return!1};p._extensions[".js"]=function(a,f){var c=m.readFileSync(f,"utf8");a._compile(z(c),f)};p._extensions[".json"]=function(a,f){var c=m.readFileSync(f,"utf8");try{a.exports=JSON.parse(z(c))}catch(l){throw l.message=f+": "+l.message,l;}}}function G(v,y){function w(b){if("string"!==typeof b)return b;if(!t&&~b.indexOf("x"))throw errnoException("ENOSYS","fs.open(O_EXCL)");switch(b){case "r":return B;
case "rs":return B|k;case "r+":return q;case "rs+":return q|k;case "w":return O_TRUNC|h|n;case "wx":case "xw":return O_TRUNC|h|n|t;case "w+":return O_TRUNC|h|q;case "wx+":case "xw+":return O_TRUNC|h|q|t;case "a":return l|h|n;case "ax":case "xa":return l|h|n|t;case "a+":return l|h|q;case "ax+":case "xa+":return l|h|q|t}throw Error("Unknown file open flag: "+b);}function z(b,u,e){e={};var a=x.pop();e.item=b;e.flags=w(u);e.position=u&l?b.size:0;r[a]=e;return a}function m(b){var a,e;for(e in f){if(-1!==
b.lastIndexOf(e)){var d=s.resolve(b).slice(b.lastIndexOf(e),b.length).split(s.sep);a=f;try{for(var g=0;g<d.length-1;g++)a=a[d[g]].items;a=a[d[d.length-1]];break}catch(c){}}a=void 0}return a}function p(b){b.atime=new Date(b.atime);b.ctime=new Date(b.ctime);b.mtime=new Date(b.mtime);if(b.content)b.content=new Buffer(b.content,"binary"),b.size=b.content.length,b.isDirectory=function(){return!1};else{b.isDirectory=function(){return!0};for(var a in b.items)p(b.items[a])}}var s=require("path"),a=require("fs"),
A=require("zlib"),f={},c=process.binding("constants"),l=c.O_APPEND||0,h=c.O_CREAT||0,t=c.O_EXCL||0,B=c.O_RDONLY||0,q=c.O_RDWR||0,k=c.O_SYNC||0,n=c.O_WRONLY||0,d={};d.readdir=a.readdir;d.readdirSync=a.readdirSync;d.stat=a.stat;d.statSync=a.statSync;d.realpathSync=a.realpathSync;d.open=a.open;d.openSync=a.openSync;d.read=a.read;d.readSync=a.readSync;d.close=a.close;d.closeSync=a.closeSync;d.fstat=a.fstat;d.fstatSync=a.fstatSync;for(var x=[],c=0;255>c;c++)x[c]=32767-c;var r={};(function(b,d){for(var e=
0,C=b.length,g=0;g<C;g++){var c=new Buffer(a.readFileSync(s.resolve(b[g]),"binary"),"base64");A.inflate(c,function(b,a){if(!b){var g=JSON.parse(a.toString()),c;for(c in g)p(g[c]),f[c]=g[c]}if(++e==C)return d()})}})(v,function(){a.fstat=function(b,a){d.fstat(b,function(e,d){return e&&void 0!==r[b]?a(null,r[b].item):a(e,d)})};a.fstatSync=function(b){try{return d.fstatSync(b)}catch(a){if(void 0!==r[b])return r[b].item;throw a;}};a.stat=function(b,a){d.stat(b,function(e,d){if(e){var g=m(b);if(g)return a(null,
g)}return a(e,d)})};a.statSync=function(b){try{return d.statSync(b)}catch(a){if(b=m(b))return b;throw a;}};a.read=function(b,a,e,c,g,f){d.read(b,a,e,c,g,function(a,d,u){if(a){var h,k;a=r[b];if(a.flags&n)throw Error("EBADF");if(a.item.isDirectory())throw Error("EISDIR");e=e||0;c=c||0;if(0===c)return f(null,0,u);k=a.item;d=0>g||null===g||isNaN(Number(g))?a.position:g;h=Math.min(k.content.length,d+c);k.content.copy(u,e,d,h);a.position=h;return f(null,h-d,u)}return f(a,d,u)})};a.readSync=function(b,a,
e,c,g){try{return d.readSync(b,a,e,c,g)}catch(f){var h;b=r[b];if(b.flags&n)throw Error("EBADF");if(b.item.isDirectory())throw Error("EISDIR");e=e||0;c=c||0;if(0===c)return 0;h=b.item;g=0>g||null===g||isNaN(Number(g))?b.position:g;c=Math.min(h.size,g+c);h.content.copy(a,e,g,c);b.position=c;return c-g}};a.realpathSync=function(b,a){try{return d.realpathSync(b,a)}catch(c){return b}};a.readdir=function(b,a){d.readdir(b,function(d,c){if(d)try{return a(null,Object.keys(m(b).items))}catch(g){}return a(d,
c)})};a.readdirSync=function(a){try{return d.readdirSync(a)}catch(c){try{return Object.keys(m(a).items)}catch(e){throw c;}}};a.open=function(a,c,e,f){void 0===f&&(f=e,e=438);d.open(a,c,e,function(d,h){if(d){var k=m(a);if(k)return f(null,z(k,c,e))}return f(d,h)})};a.openSync=function(a,c,e){try{return d.openSync(a,c,e)}catch(f){if(m(a))return z(m(a),c,e);throw f;}};a.close=function(a,c){d.close(a,function(d){return d?(delete r[a],x.push(a),c(null)):c(d)})};a.closeSync=function(a){try{return d.closeSync(a)}catch(c){delete r[a],
x.push(a)}};return y()})}var H=require("path").join(__dirname,"native_modules");(function(v,y,w){G(v,function(){F(y);w()})})([require("path").join(__dirname,D)],H,function(){var v=require("module")._load(E,module,!0);"function"===typeof v&&v(process.argv)})};process.argv[1]===__filename&&module.exports(process.argv[2],process.argv[3],process.argv[4]);
